services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    volumes:
      - ./conf/prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./conf/grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus      
  redis:
    image: redis/redis-stack-server
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5      
  mocks:
    image: mjguisado/mocks:latest
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile.mocks
    container_name: mocks
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: package*.json
        - action: sync
          path: ./mocks
          target: /usr/src/app/mocks
    ports:
      - 3030:3030
  speedis:
    image: mjguisado/speedis:latest
    pull_policy: build
    build:  
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: speedis
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: package*.json
        - action: sync
          path: ./src
          target: /usr/src/app/src
        - action: sync+restart
          path: ./conf
          target: /usr/src/app/conf       
    deploy:
      resources:
        limits:
          cpus: "5"
    ports:
      - 3001:3001
      - 3003:3003
      - 9229:9229
    depends_on:
      - redis
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8405:8405
    volumes:
      - ./conf/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./conf/haproxy/certs:/usr/local/etc/haproxy/certs:ro
    depends_on:
      - speedis
volumes:
  prom_data: