{
 "title": "Speedis",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total number of responses by Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_responses_total{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_HIT\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    },
    {
     "expr": "rate(http_responses_total{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_MISS\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    },
    {
     "expr": "rate(http_responses_total{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_HIT\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    },
    {
     "expr": "rate(http_responses_total{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_MISS\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    },
    {
     "expr": "rate(http_responses_total{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_FAIL_HIT\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    }
   ]
  },
  {
   "title": "Responses duration by Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_responses_duration_sum{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_HIT\"}[$__rate_interval]) / rate(http_responses_duration_count{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_HIT\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    },
    {
     "expr": "rate(http_responses_duration_sum{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_MISS\"}[$__rate_interval]) / rate(http_responses_duration_count{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_MISS\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    },
    {
     "expr": "rate(http_responses_duration_sum{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_HIT\"}[$__rate_interval]) / rate(http_responses_duration_count{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_HIT\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    },
    {
     "expr": "rate(http_responses_duration_sum{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_MISS\"}[$__rate_interval]) / rate(http_responses_duration_count{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_MISS\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    },
    {
     "expr": "rate(http_responses_duration_sum{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_FAIL_HIT\"}[$__rate_interval]) / rate(http_responses_duration_count{job=\"speedis\",origin=\"mocks\",cacheStatus=\"TCP_REFRESH_FAIL_HIT\"}[$__rate_interval])",
     "legendFormat": "{{cacheStatus}}"
    }
   ]
  },
  {
   "title": "Responses duration by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "rate(http_responses_duration_sum{job=\"speedis\",origin=\"mocks\"}[$__rate_interval]) / rate(http_responses_duration_count{job=\"speedis\",origin=\"mocks\"}[$__rate_interval])",
     "legendFormat": "{{statusCode}}"
    }
   ]
  }
 ]
}