apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: speedis
data:
  haproxy.cfg: |
    defaults
      timeout connect 10s
      timeout client 30s
      timeout server 30s
    frontend http_front
      bind *:80
      default_backend app_backend
    backend app_backend
      server app my-app:3000 check