apiVersion: v1
kind: Service
metadata:
  name: mocks
  namespace: cache
spec:
  selector:
    app: mocks
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      name: http
  type: ClusterIP